name: pmd 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  pmd-analyse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Run PMD Static Code Analysis 
      uses: pmd/pmd-github-action@v1
      with:
        rulesets: ’java-basic’
    - name: Extract PMD violations count
      id: extract
      run: |
        echo "::set-output name=violations::$(echo '${{ steps.pmd.outputs.report }}' | grep -o 'Problem: ' | wc -l)"

    - name: Check violations threshold
      run: |
          THRESHOLD=10 # Set your threshold here
          if [ "${{ steps.extract.outputs.violations }}" -gt $THRESHOLD ]; then
            echo "Number of violations exceeds threshold. Failing workflow."
            exit 1
          fi
    
