name: pmd 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  pmd-analyse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '21'
        
    - name: Run PMD Static Code Analysis 
      uses: pmd/pmd-github-action@v4
      with:
        rulesets: ’java-basic’
    - name: Fail build if there are violations
      if: steps.pmd.outputs.violations != 0
      run: exit 1
    
